title: Hist
author:
  name: Hist
  email: contact@hist.games
description: > # this means to ignore newlines until "twitter_username:"
  We make deep strategy games for people who love history.

# url: "https://histgames.com"
# baseurl: ""
url: "https://ad1337.github.io"
baseurl: "/hist-site"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  hide_site_feed_link: true
  social_links:

  - title: Twitch
    icon: twitch
    url: "https://twitch.tv/lucasgmolina"
  
  - title: Discord
    icon: discord
    url: "https://discord.gg/yourserver"
  
  - title: Steam
    icon: steam
    url: "https://discord.gg/yourserver"
  
  - title: Instagram
    icon: instagram
    url: "https://twitch.tv/lucasgmolina"
  
  - title: Tiktok
    icon: tiktok
    url: "https://discord.gg/yourserver"
  
  - title: Facebook
    icon: facebook
    url: "https://discord.gg/yourserver"
  
  - title: X
    icon: x
    url: "https://discord.gg/yourserver"

  - title: Bluesky
    icon: bluesky
    url: "https://discord.gg/yourserver"

  - title: YouTube
    icon: youtube
    url: "https://discord.gg/yourserver"
  
  - title: Reddit
    icon: reddit
    url: "https://discord.gg/yourserver"
  

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

titles_from_headings:
  enabled: false
